version: '3.8'

services:
  db:
    image: postgres:15
    container_name: gardenshop-db
    restart: always
    environment:
      POSTGRES_DB: gardenshop
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: shop
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gardenshop.com
      PGADMIN_DEFAULT_PASSWORD: shop
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  pgdata:
  pgadmin-data:
